#!/bin/sh
#echo '$*:' "$*" >> /tmp/ssh.log
if [ "$1" = "" ]; then
	exit
elif [ "$*" = "bash -l" ] || [ "$*" = "sudo -E -H bash -l" ]; then
	while read -r aline; do
#		echo "$aline" >> /tmp/ssh.log
		if [ "$aline" = "exit" ]; then
			exit
		elif [ "$aline" = "echo; printf /vagrant" ]; then
			echo
			printf "/vagrant"
		elif [ "$aline" = "shutdown -h now" ]; then
			kill -12 1
		elif [ "${aline%% *}" = "hostnamectl" ]; then
			pcd-ctl hostname "${aline##* }"
		else
			echo ""
		fi
	done
elif [ "$1" = "scp" ]; then
	printf "\0"
	read -r _ size _
	printf "\0"
	data="$(dd bs="$size" count=1 2>/dev/null)"
	#echo "data: $data" >> /tmp/ssh.log
	echo "$data" | while read -r aline; do
		if echo "$aline" | grep -q "ifconfig"; then
			$aline
		elif [ "${aline%% *}" = "hostname" ]; then
			pcd-ctl hostname "${aline##* }"
		fi
	done
	printf "\0"
	exit
else
#	echo "don't know how to handle $*" >> /tmp/ssh.log
	exit
fi
